---
- name: Look for config on a juniper box
  hosts:
    - all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no

    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - juniper_junos_facts:
        config_format: text
        host: "{{ ansible_host }}"
        user: "{{ username }}"
        passwd: "{{ password }}"
